### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by sssergy** [Snowgem/Snowgem#1]
segmentation fault if share accepted

**Comment by vtnplus** [comment]
hi master.
this problem
what is fix 
/usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found

**Comment by vtnplus** [comment]
./snowgemd
./snowgemd: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by ./snowgemd)
./snowgemd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./snowgemd)
./snowgemd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./snowgemd)
./snowgemd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./snowgemd)
./snowgemd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./snowgemd)
./snowgemd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./snowgemd)

**Comment by Snowgem** [comment]
Please refer to this one: https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

**Comment by Snowgem** [comment]
Moreover, it's before the Launch, so the crash is expected behavior to prevent premine.
