### ISSUE TITLE
Can't setup wallet on Mac

### ISSUE THREAD

**Issue by jp26jp** [Snowgem/Snowgem#11]
I've downloaded the latest wallet and I've run the setup.sh file but when I try to open the wallet, I get this error:

> A general unexpected critical error has occurred:
> com.eclipsesource.json.ParseException: Expected value at 1:1
> See the console output for more detailed error information!

**Comment by Snowgem** [comment]
have you run setup.sh file?
Could you run snowgemd only to see the error?

**Comment by jp26jp** [comment]
> I've downloaded the latest wallet and **I've run the setup.sh**

I'll try running snowgemd when I'm back at my comp

**Comment by Snowgem** [comment]
could you join our discord and DM #Txid?
https://discord.gg/7a7XRZr
