### ISSUE TITLE
Error download zeromq 4.3.1 when compiling for ubuntu

### ISSUE THREAD

**Issue by unyil** [Snowgem/Snowgem#21]
I got error download zeromq when compiling for ubuntu.
This error resolved by removing backslash in file Snowgem/depends/packages/zeromq.mk
Line 3
$(package)_download_path=https://github.com/zeromq/libzmq/releases/download/v$($(package)_version)/
to 
$(package)_download_path=https://github.com/zeromq/libzmq/releases/download/v$($(package)_version)

**Comment by Snowgem** [comment]
thanks so much. Updated
