### ISSUE TITLE
Proposed solution for alleged abbreviation clash with Sinergia Project (SNG)

### ISSUE THREAD

**Issue by versier** [Snowgem/Snowgem#4]
Could we consider using SNW as an abbreviation? This doesn't seem to be in use by any blockchain projects that I have breifely researched. It also makes me think more of snow, where as sng reminds me of the word song.

Discliamer: I'd never heard of sinergia before this, I've just been mining snowgem and following the bitcointalk thread.

**Comment by Snowgem** [comment]
we're on talk with Sinergia Project  to resolve this problem.
